import { defineConfig } from 'vite';
import react from '@vitejs/plugin-react';
import { VitePWA } from 'vite-plugin-pwa';
import { resolve, dirname } from 'path';
import { fileURLToPath } from 'url';
import { fork } from 'child_process';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

// A simple plugin to start the local DB server automatically during development
function localDbServerPlugin() {
  let serverProcess = null;
  return {
    name: 'local-db-server',
    configureServer(server) {
      if (process.env.NODE_ENV === 'production' || process.env.VITEST) return;
      
      console.log('\x1b[36m%s\x1b[0m', '>> [Vite Plugin] Starting local DB server on port 3001...');
      serverProcess = fork(resolve(__dirname, 'server.js'));
      
      serverProcess.on('error', (err) => {
        console.error('Failed to start local DB server:', err);
      });

      serverProcess.on('exit', (code) => {
        if (code && code !== 0) {
          console.error(`Local DB server exited with code ${code}`);
        }
      });

      const killChild = () => { if (serverProcess) serverProcess.kill(); };
      process.on('exit',   killChild);
      process.on('SIGTERM', () => { killChild(); process.exit(0); });
      process.on('SIGINT',  () => { killChild(); process.exit(0); });
    },
    closeBundle() {
      if (serverProcess) {
        console.log('\x1b[36m%s\x1b[0m', '>> [Vite Plugin] Stopping local DB server...');
        serverProcess.kill();
      }
    }
  };
}

export default defineConfig({
  plugins: [
    react(),
    localDbServerPlugin(),
    VitePWA({
      registerType: 'autoUpdate',
      includeAssets: [
        'assets/favicon.ico',
        'assets/favicon.svg',
        'pwa-192x192.svg',
        'pwa-512x512.svg',
      ],
      manifest: {
        name: 'Andrés Gallo P. — BIM Developer & Structural Tools',
        short_name: 'AGP Tools',
        description: 'Portfolio BIM y herramientas de cálculo estructural: perfiles ICHA, escaleras metálicas, calculadora de perfiles y más.',
        theme_color: '#0b1220',
        background_color: '#020617',
        display: 'standalone',
        start_url: '/',
        scope: '/',
        categories: ['productivity', 'utilities', 'education'],
        icons: [
          {
            src: 'pwa-192x192.svg',
            sizes: '192x192',
            type: 'image/svg+xml',
            purpose: 'any',
          },
          {
            src: 'pwa-512x512.svg',
            sizes: '512x512',
            type: 'image/svg+xml',
            purpose: 'any maskable',
          },
        ],
      },
      workbox: {
        maximumFileSizeToCacheInBytes: 5000000,
        // Precache the app shell (JS, CSS, HTML) — auto-generated by Workbox
        globPatterns: ['**/*.{js,css,html,svg,woff2}'],
        // Runtime caching strategies for assets loaded on demand
        runtimeCaching: [
          {
            // Project images (webp) — cache first, serve from cache offline
            urlPattern: /\.(?:webp|png|jpg|jpeg|gif)$/i,
            handler: 'CacheFirst',
            options: {
              cacheName: 'images-cache',
              expiration: {
                maxEntries: 80,
                maxAgeSeconds: 30 * 24 * 60 * 60, // 30 days
              },
            },
          },
          {
            // Google Fonts stylesheets
            urlPattern: /^https:\/\/fonts\.googleapis\.com\/.*/i,
            handler: 'StaleWhileRevalidate',
            options: {
              cacheName: 'google-fonts-stylesheets',
            },
          },
          {
            // Google Fonts webfont files
            urlPattern: /^https:\/\/fonts\.gstatic\.com\/.*/i,
            handler: 'CacheFirst',
            options: {
              cacheName: 'google-fonts-webfonts',
              expiration: {
                maxEntries: 10,
                maxAgeSeconds: 365 * 24 * 60 * 60, // 1 year
              },
            },
          },
          {
            // Font Awesome CDN
            urlPattern: /^https:\/\/cdnjs\.cloudflare\.com\/ajax\/libs\/font-awesome\/.*/i,
            handler: 'CacheFirst',
            options: {
              cacheName: 'font-awesome-cache',
              expiration: {
                maxEntries: 10,
                maxAgeSeconds: 365 * 24 * 60 * 60,
              },
            },
          },
          {
            // 3D models (GLB) — cache on first use for offline 3D viewer
            urlPattern: /\.(?:glb|gltf)$/i,
            handler: 'CacheFirst',
            options: {
              cacheName: 'models-cache',
              expiration: {
                maxEntries: 5,
                maxAgeSeconds: 90 * 24 * 60 * 60, // 90 days
              },
            },
          },
        ],
        // SPA navigation fallback
        navigateFallback: 'index.html',
        navigateFallbackDenylist: [/^\/api\//],
      },
    }),
  ],
  root: './',
  resolve: {
    alias: {
      stream: 'stream-browserify',
      path: 'path-browserify',
      events: 'events',
    },
  },
  build: {
    outDir: 'dist',
    rollupOptions: {
      input: {
        main: resolve(__dirname, "index.html"),
      },
      output: {
        manualChunks(id) {
          // Three.js + React Three Fiber + Drei → separate "vendor-3d" chunk
          if (id.includes('three') || id.includes('@react-three')) {
            return 'vendor-3d';
          }
          // web-ifc → separate "vendor-ifc" chunk (WASM loader, rarely used)
          if (id.includes('web-ifc')) {
            return 'vendor-ifc';
          }
          // Export libraries (ExcelJS, jsPDF, xlsx) → "vendor-export"
          if (id.includes('exceljs') || id.includes('jspdf') || id.includes('xlsx-js-style')) {
            return 'vendor-export';
          }
          // Chart.js → "vendor-chart"
          if (id.includes('chart.js')) {
            return 'vendor-chart';
          }
          // DnD Kit → "vendor-dnd"
          if (id.includes('@dnd-kit')) {
            return 'vendor-dnd';
          }
          // React core + Router + Framer Motion → "vendor-react"
          if (
            id.includes('node_modules/react/') ||
            id.includes('node_modules/react-dom/') ||
            id.includes('react-router') ||
            id.includes('framer-motion')
          ) {
            return 'vendor-react';
          }
        },
      },
    },
  },
  server: {
    open: true,
  },
});

